export type SpeechLanguage = { code: string; label: string };

/** Browser speech-recognition locales, covering the widely supported set. */
export const SPEECH_LANGUAGES: SpeechLanguage[] = [
  { code: "af-ZA", label: "Afrikaans" },
  { code: "am-ET", label: "አማርኛ (Amharic)" },
  { code: "ar-SA", label: "العربية (Arabic)" },
  { code: "az-AZ", label: "Azərbaycan" },
  { code: "bn-BD", label: "বাংলা (Bengali)" },
  { code: "bg-BG", label: "Български" },
  { code: "ca-ES", label: "Català" },
  { code: "cs-CZ", label: "Čeština" },
  { code: "da-DK", label: "Dansk" },
  { code: "de-DE", label: "Deutsch" },
  { code: "el-GR", label: "Ελληνικά" },
  { code: "en-US", label: "English (US)" },
  { code: "en-GB", label: "English (UK)" },
  { code: "en-IN", label: "English (India)" },
  { code: "es-ES", label: "Español (España)" },
  { code: "es-MX", label: "Español (México)" },
  { code: "et-EE", label: "Eesti" },
  { code: "eu-ES", label: "Euskara" },
  { code: "fa-IR", label: "فارسی (Persian)" },
  { code: "fi-FI", label: "Suomi" },
  { code: "fil-PH", label: "Filipino" },
  { code: "fr-FR", label: "Français" },
  { code: "gl-ES", label: "Galego" },
  { code: "gu-IN", label: "ગુજરાતી" },
  { code: "he-IL", label: "עברית (Hebrew)" },
  { code: "hi-IN", label: "हिन्दी (Hindi)" },
  { code: "hr-HR", label: "Hrvatski" },
  { code: "hu-HU", label: "Magyar" },
  { code: "hy-AM", label: "Հայերեն" },
  { code: "id-ID", label: "Bahasa Indonesia" },
  { code: "is-IS", label: "Íslenska" },
  { code: "it-IT", label: "Italiano" },
  { code: "ja-JP", label: "日本語 (Japanese)" },
  { code: "jv-ID", label: "Basa Jawa" },
  { code: "ka-GE", label: "ქართული" },
  { code: "kk-KZ", label: "Қазақша" },
  { code: "km-KH", label: "ភាសាខ្មែរ" },
  { code: "kn-IN", label: "ಕನ್ನಡ" },
  { code: "ko-KR", label: "한국어 (Korean)" },
  { code: "lo-LA", label: "ລາວ" },
  { code: "lt-LT", label: "Lietuvių" },
  { code: "lv-LV", label: "Latviešu" },
  { code: "ml-IN", label: "മലയാളം" },
  { code: "mn-MN", label: "Монгол" },
  { code: "mr-IN", label: "मराठी" },
  { code: "ms-MY", label: "Bahasa Melayu" },
  { code: "my-MM", label: "မြန်မာ" },
  { code: "ne-NP", label: "नेपाली" },
  { code: "nl-NL", label: "Nederlands" },
  { code: "nb-NO", label: "Norsk bokmål" },
  { code: "pa-IN", label: "ਪੰਜਾਬੀ" },
  { code: "pl-PL", label: "Polski" },
  { code: "pt-BR", label: "Português (Brasil)" },
  { code: "pt-PT", label: "Português (Portugal)" },
  { code: "ro-RO", label: "Română" },
  { code: "ru-RU", label: "Русский (Russian)" },
  { code: "si-LK", label: "සිංහල" },
  { code: "sk-SK", label: "Slovenčina" },
  { code: "sl-SI", label: "Slovenščina" },
  { code: "sr-RS", label: "Српски" },
  { code: "su-ID", label: "Basa Sunda" },
  { code: "sv-SE", label: "Svenska" },
  { code: "sw-KE", label: "Kiswahili" },
  { code: "ta-IN", label: "தமிழ்" },
  { code: "te-IN", label: "తెలుగు" },
  { code: "th-TH", label: "ไทย (Thai)" },
  { code: "tr-TR", label: "Türkçe" },
  { code: "uk-UA", label: "Українська" },
  { code: "ur-PK", label: "اردو (Urdu)" },
  { code: "uz-UZ", label: "O‘zbek" },
  { code: "vi-VN", label: "Tiếng Việt" },
  { code: "zh-CN", label: "中文 (普通话)" },
  { code: "zh-HK", label: "中文 (粵語)" },
  { code: "zh-TW", label: "中文 (台灣)" },
  { code: "zu-ZA", label: "isiZulu" },
];

/** Picks the closest supported locale for the visitor's browser language. */
export function detectLanguage(preferred?: string): string {
  const wanted = (preferred ?? "").toLowerCase();
  if (!wanted) return "en-US";
  const exact = SPEECH_LANGUAGES.find((l) => l.code.toLowerCase() === wanted);
  if (exact) return exact.code;
  const base = wanted.split("-")[0];
  const partial = SPEECH_LANGUAGES.find((l) => l.code.toLowerCase().startsWith(`${base}-`));
  return partial?.code ?? "en-US";
}
