/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksRouteImport } from './routes/books'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiPhotoToLineartRouteImport } from './routes/api/photo-to-lineart'
import { Route as GalleryIdRouteImport } from './routes/gallery.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotoToLineartRoute = ApiPhotoToLineartRouteImport.update({
  id: '/api/photo-to-lineart',
  path: '/api/photo-to-lineart',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/gallery/$id',
  path: '/gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/github': typeof GithubRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/photo-to-lineart': typeof ApiPhotoToLineartRoute
  '/gallery/$id': typeof GalleryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/github': typeof GithubRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/photo-to-lineart': typeof ApiPhotoToLineartRoute
  '/gallery/$id': typeof GalleryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/github': typeof GithubRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/photo-to-lineart': typeof ApiPhotoToLineartRoute
  '/gallery/$id': typeof GalleryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/github'
    | '/api/generate-image'
    | '/api/photo-to-lineart'
    | '/gallery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/github'
    | '/api/generate-image'
    | '/api/photo-to-lineart'
    | '/gallery/$id'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/github'
    | '/api/generate-image'
    | '/api/photo-to-lineart'
    | '/gallery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  GithubRoute: typeof GithubRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiPhotoToLineartRoute: typeof ApiPhotoToLineartRoute
  GalleryIdRoute: typeof GalleryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photo-to-lineart': {
      id: '/api/photo-to-lineart'
      path: '/api/photo-to-lineart'
      fullPath: '/api/photo-to-lineart'
      preLoaderRoute: typeof ApiPhotoToLineartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/gallery/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  GithubRoute: GithubRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiPhotoToLineartRoute: ApiPhotoToLineartRoute,
  GalleryIdRoute: GalleryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
